In [ ]:
!pip install pandas
!pip install openpyxl

In [ ]:
! pip install pandas ast

In [ ]:
import pandas as pd
import openpyxl
df=pd.read_excel("chennai_cars.xlsx")
df

In [3]:
   
 # Extracting relevant features into a structured format
structured_data = []
for index, row in df.iterrows():
          new_car_detail = eval(row['new_car_detail'])
          new_car_overview = eval(row['new_car_overview'])
          new_car_feature = eval(row['new_car_feature'])
          new_car_specs = eval(row['new_car_specs'])
          structured_data.append({
              'Ignition Type': new_car_detail['it'],
              'Fuel Type': new_car_detail['ft'],
              'Body Type': new_car_detail['bt'],
              'Kilometers Driven': new_car_detail['km'],
              'Transmission': new_car_detail['transmission'],
              'Number of Owners': new_car_detail['ownerNo'],
              'Ownership': new_car_detail['owner'],
              'Company_Name': new_car_detail['oem'],
              'Model': new_car_detail['model'],
              'Model Year': new_car_detail['modelYear'],
              'Variant Name': new_car_detail['variantName'],
              'Price': new_car_detail['price'],
              'Price_Actual': new_car_detail['priceActual'],
              'Price_Saving': new_car_detail['priceSaving'],
              'Price_Fixed_Text': new_car_detail['priceFixedText'],
              'Trending_Text': new_car_detail['trendingText'],
              'Overview': str(new_car_overview['top']),  # Convert to string
              'Features': str(new_car_feature['top']),
              'Features_data': str(new_car_feature['data']),
              #'Features_list': str(new_car_feature['list']),  # Convert to string
              'Specifications': str(new_car_specs['top']),
              'Specifications_data': str(new_car_specs['data']),
              #'Specifications_list': str(new_car_specs['list']),# Convert to string
              'Link': row['car_links']
          })
# Convert structured data to DataFrame for better visualization
structured_df = pd.DataFrame(structured_data)
structured_df_head = structured_df.head()  # Get the first few rows for display

In [4]:
structured_df.to_csv('chennai.csv', index=False)

In [5]:
df=pd.read_csv("chennai.csv")

In [6]:
import ast     
# Function to extract values from the Overview column
def extract_overview_values(overview_str):
    overview_list = ast.literal_eval(overview_str)
    return {item['key']: item['value'] for item in overview_list}

 # Apply the function to extract values and create new columns
overview_data = df['Overview'].apply(extract_overview_values).apply(pd.Series)

# Rename the new columns to avoid duplicates
overview_data.columns = [f'Overview_{col}' for col in overview_data.columns]

 # Concatenate the new columns to the original DataFrame
df = pd.concat([df, overview_data], axis=1)

In [ ]:
import pandas as pd
from IPython.display import display

# Display the updated dataframe with new columns
display(df[['Overview_Registration Year', 'Overview_Insurance Validity', 'Overview_Fuel Type', 'Overview_Seats', 
'Overview_Kms Driven', 'Overview_RTO', 'Overview_Ownership', 'Overview_Engine Displacement', 
'Overview_Transmission', 'Overview_Year of Manufacture']])

In [7]:
df.to_csv('chennai1.csv', index=False)

In [8]:
df=pd.read_csv("chennai1.csv")

In [9]:
# Define the features to check
features_list = [
          'Power Steering', 'Power Windows Front', 'Air Conditioner', 
          'Heater', 'Adjustable Head Lights', 
          'Manually Adjustable Exterior Rear View Mirror', 
          'Centeral Locking', 'Child Safety Locks', 
          'Fog Lights Front', 'Anti Lock Braking System', 
          'Cd Player', 'Brake Assist', 
          'Electric Folding Rear View Mirror', 'Radio', 
          'Fog Lights Rear', 'Power Door Locks'
      ]
      
      # Initialize new columns for each feature
for feature in features_list:
          df[feature] = df['Features'].apply(lambda x: 1 if feature in x else 0)
import pandas as pd
from IPython.display import display
display(df.head())  # Display only the first few rows

,Ignition Type,Fuel Type,Body Type,Kilometers Driven,Transmission,Number of Owners,Ownership,Company_Name,Model,Model Year,...,Centeral Locking,Child Safety Locks,Fog Lights Front,Anti Lock Braking System,Cd Player,Brake Assist,Electric Folding Rear View Mirror,Radio,Fog Lights Rear,Power Door Locks
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,0,0,1,1,0,1,0,1,0,0
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,0,1,0,1,0,0,0,0,0,0
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,0,0,1,1,0,1,0,1,0,0
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,1,0,1,0,1,0,0,0,0,1
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,1,0,1,1,1,0,0,0,0,0

In [10]:
df.to_csv('chennai2.csv', index=False)

In [11]:
df=pd.read_csv("chennai2.csv")

In [ ]:
 
# Define the features to check
features_data_list = [
          'Remote Trunk Opener', 'Remote Fuel Lid Opener', 'Low Fuel Warning Light', 
          'Accessory Power Outlet', 'Vanity Mirror', 'Rear Seat Headrest', 
          'Cup Holders Front', 'Digital Odometer', 'Electronic Multi Tripmeter', 
          'Fabric Upholstery', 'Glove Compartment', 'Digital Clock', 
          'Wheel Covers', 'Power Antenna', 'Chrome Grille', 
          'Day Night Rear View Mirror', 'Passenger Side Rear View Mirror', 
          'Halogen Headlamps', 'Rear Seat Belts', 'Door Ajar Warning', 
          'Side Impact Beams', 'Front Impact Beams', 
          'Centrally Mounted Fuel Tank', 'Engine Immobilizer', 'Anti Theft Device'
      ]    
# Initialize new columns for each feature
for feature in features_data_list:
    df[feature] = df['Features_data'].apply(lambda x: 1 if feature in x else 0)
import pandas as pd
from IPython.display import display
display(df.head())  # Display only the first few rows

In [13]:
df.to_csv('chennai3.csv', index=False)

In [14]:
df=pd.read_csv('chennai3.csv')

In [15]:
import ast
structured_data = []
for index, row in df.iterrows():
          Specifications = ast.literal_eval(row['Specifications'])
          Specifications_data= ast.literal_eval(row['Specifications_data'])
          structured_data.append({
              'Engine_CC': next((item['value'] for item in Specifications if item['key'] == 'Engine'), None),
              'Max Power': next((item['value'] for item in Specifications if item['key'] == 'Max Power'), None),
              'Torque': next((item['value'] for item in Specifications if item['key'] == 'Torque'), None),
              'Seats': next((item['value'] for item in Specifications if item['key'] == 'Seats'), None),
              'Wheel Size': next((item['value'] for item in Specifications if item['key'] == 'Wheel Size'), None),
              'Mileage': next((item['value'] for item in Specifications if item['key'] == 'Mileage'), None)
              
          })
# Convert structured data to DataFrame for better visualization
structured_df = pd.DataFrame(structured_data)
structured_df_head = structured_df.head()  # Get the first few rows for display

In [16]:
df = pd.concat([df, structured_df], axis=1)

In [17]:
df.to_csv('chennai4.csv', index=False)

In [18]:

df=pd.read_csv('chennai4.csv')
df_head = df.head()
import pandas as pd
import ast
# Function to extract keys and values from Specifications_data
def extract_specifications(spec_data):
    try:
        specs = ast.literal_eval(spec_data)
        return [(item['key'], item['value']) for sublist in specs for item in sublist['list']]
    except:
        return []

# Create a new DataFrame to hold the extracted specifications
specifications = []
for index, row in df.iterrows():
    extracted = extract_specifications(row['Specifications_data'])
    specifications.append({'Model': row['Model'], **dict(extracted)})

specifications_df = pd.DataFrame(specifications)
specifications_head = specifications_df.head()

In [ ]:
specifications_df

In [20]:
df = pd.concat([df, specifications_df], axis=1)

In [ ]:
df

In [22]:
df.to_csv('chennai5.csv', index=False)

In [24]:

delhi_df =pd.read_csv('Delhi.csv')
jaipur_df =pd.read_csv('Jaipur.csv')
channai_df =pd.read_csv('Chennai.csv')
kolkata_df = pd.read_csv('Kolkata.csv')
bangalore_df =pd.read_csv('Bangalore.csv')
hyderabad_df =pd.read_csv('Hyderabad.csv')
combined_df = pd.concat([delhi_df, jaipur_df, channai_df, kolkata_df, bangalore_df, hyderabad_df], ignore_index=True)
combined_df

,City,Ignition Type,Fuel Type,Body Type,Kilometers Driven,Transmission,Number of Owners,Ownership,Company_Name,Model,...,Super Charger,Turning Radius,Top Speed,Acceleration,Gross Weight,Front Tread,Rear Tread,BoreX Stroke,Compression Ratio,Ground Clearance Unladen
0,Delhi,0,Diesel,SUV,"10,000",Automatic,1,1st Owner,Kia,Kia Seltos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Delhi,0,Petrol,SUV,"57,437",Manual,2,2nd Owner,Hyundai,Hyundai Creta,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN
2,Delhi,0,Petrol,SUV,"8,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz GLC,...,NaN,NaN,217 Kmph,NaN,2360kg,NaN,NaN,NaN,NaN,NaN
3,Delhi,0,Petrol,Hatchback,"28,151",Manual,2,2nd Owner,Maruti,Maruti Swift,...,NaN,4.8,NaN,NaN,1335,1530,1530,NaN,NaN,NaN
4,Delhi,0,Petrol,SUV,"60,000",Manual,1,1st Owner,Hyundai,Hyundai Creta,...,No,5.3 metres,165 Kmph,10.5 Seconds,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Hyderabad,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,...,No,5.6 metres,175 kmph,12.5 Seconds,2450kg,NaN,NaN,NaN,NaN,NaN
8365,Hyderabad,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,...,No,5.75 metres,250 Kmph,6.4 Seconds,2360kg,1559mm,1605mm,NaN,NaN,NaN
8366,Hyderabad,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,...,No,5.6,235kmph,7.5,NaN,1605mm,1630mm,NaN,NaN,NaN
8367,Hyderabad,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,...,No,5.1m,154.19 kmph,13.25 Seconds,NaN,1540 mm,1530 mm,76x82.5,NaN,209 mm
8368,Hyderabad,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,...,No,5.4 metres,155 Kmph,13.3 Seconds,2300kg,1510mm,1510mm,NaN,NaN,NaN

In [26]:
combined_df.to_csv('Car_Details.csv')